apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels: {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
