apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasource.yml: |
    apiVersion: 1
    deleteDatasources:
      - name: PostgreSQL
        orgId: 1
    datasources:
      - name: PostgreSQL
        type: postgres
        access: proxy
        orgId: 1
        url: {{ include "grafana.postgresHost" . }}:5432
        database: {{ .Values.postgresql.database }}
        user: $__env{GF_DS_POSTGRES_USER}
        secureJsonData:
          password: $__env{GF_DS_POSTGRES_PASSWORD}
        jsonData:
          sslmode: disable
          postgresVersion: 1600
        isDefault: true
        editable: true
        version: 1
