apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasource.yml: |
    apiVersion: 1
    deleteDatasources:
      - name: PostgreSQL
        orgId: 1
    datasources:
      - name: PostgreSQL
        type: postgres
        access: proxy
        orgId: 1
        url: {{ include "grafana.postgresHost" . }}:5432
        database: {{ .Values.postgresql.database }}
        user: {{ .Values.postgresql.username }}
        secureJsonData:
          password: {{ .Values.postgresql.password }}
        jsonData:
          sslmode: disable
          postgresVersion: 1600
        isDefault: true
        editable: true
        version: 1
