apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: PostgreSQL
        type: postgres
        access: proxy
        url: {{ include "grafana.postgresHost" . }}:5432
        database: medical_data
        user: pipeline
        secureJsonData:
          password: changeme
        jsonData:
          sslmode: disable
          postgresVersion: 1600
        isDefault: true
        editable: true
