apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingestion.fullname" . }}-kaggle
  labels:
    {{- include "ingestion.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAGGLE_USERNAME: {{ .Values.kaggle.username | quote }}
  KAGGLE_KEY: {{ .Values.kaggle.key | quote }}
